### ISSUE TITLE
sendNotification function 

### ISSUE THREAD

**Issue by fasilminale** [nemac95pn/mychat#1]
TypeError: Cannot read property 'receiver_id' of undefined
    at exports.sendNotification.functions.database.ref.onWrite.event (/user_code/index.js:9:45)
    at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:112:27)
    at next (native)
    at /user_code/node_modules/firebase-functions/lib/cloud-functions.js:28:71
    at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24:12)
    at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:82:36)
    at /var/tmp/worker/worker.js:716:24
    at process._tickDomainCallback (internal/process/next_tick.js:135:7)

**Comment by nemac95pn** [comment]
how to fix this error?

**Comment by fasilminale** [comment]
i forgot how i was fix it but see this file
index.js: https://hastebin.com/osogumovej.js

**Comment by fasilminale** [comment]
i forgot how i was fix it but see this file  [ index.js ](https://hastebin.com/osogumovej.js)
